<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>netstandard2.1</TargetFramework>
	<ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<LangVersion>Preview</LangVersion>

	<Authors>DMG</Authors>
	<Company>Cygnus Instruments Ltd</Company>
	<Product>TM-Link</Product>
	<Description>Models for Cygnus Gauges</Description>
	<PackageId>Cygnus.Models</PackageId>
	<Title>Cygnus.Models</Title>
	<Copyright>© 2026 Cygnus Instruments Ltd</Copyright>
	<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	<!--Auto-generate NuGet package-->
	<GenerateAssemblyInfo>true</GenerateAssemblyInfo>
	<RepositoryUrl>https://github.com/c49nu5/tmlink-dotnet-api</RepositoryUrl>
	<PackageIcon>icon.png</PackageIcon>
	<PackageLicenseExpression>MIT</PackageLicenseExpression>
	<PackageReadmeFile>README.md</PackageReadmeFile>	  
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\icon.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\LICENSE.txt">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <None Update="README.md">
      <PackagePath>\</PackagePath>
      <Pack>True</Pack>
    </None>
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="MessagePack" Version="3.1.6" />
  </ItemGroup>

</Project>
