<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<Authors>DMG</Authors>
	<Company>Cygnus Instruments Ltd</Company>
	<Product>TM-Link</Product>
	<Description>Services for Cygnus Gauges</Description>
	<PackageId>Cygnus.Services</PackageId>
	<Title>Cygnus.Services</Title>
	<Copyright>© 2026 Cygnus Instruments Ltd</Copyright>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cygnus.Interfaces\Cygnus.Interfaces.csproj" />
  </ItemGroup>

</Project>
