name: CI Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@6.0.2
      with:
        fetch-depth: 0
        persist-credentials: true

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v4.5.0
      with:
        versionSpec: '6.7.x'
      
    - name: Determine Version
      id: version_step # step id used as a reference for output values
      uses: gittools/actions/gitversion/execute@v4.5.0

    - name: Display GitVersion variables
      run: |
        echo "FullSemVer (env.fullSemVer)    : ${{ env.fullSemVer }}"
        echo "SemVer (env.semVer)            : ${{ env.semVer }}"

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Install third party notices tool
      run: dotnet tool install --global ThirdLicense
      continue-on-error: true
      
    - name: Generate third party notices
      run: thirdlicense --project  ./Cygnus.BLE.API/Cygnus.BLE.API.csproj --output ./THIRD-PARTY-NOTICES.txt
      continue-on-error: true

    - name: Build
      run: dotnet build -c Release --no-restore /p:Version=${{ env.fullSemVer }}

    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal --logger trx --collect:"XPlat Code Coverage" --results-directory coverage
      
    - name: Create code coverage report
      run: |
        dotnet tool install -g dotnet-reportgenerator-globaltool
        reportgenerator -reports:coverage/*/coverage.cobertura.xml -targetdir:CodeCoverage -reporttypes:'MarkdownSummaryGithub,Cobertura'

    - name: Write to Job Summary
      run: |
        echo "### Coverage results :rocket:" >> $GITHUB_STEP_SUMMARY
        cat CodeCoverage/SummaryGithub.md >> $GITHUB_STEP_SUMMARY

    - name: Pack
      run: dotnet pack -c Release --no-restore --no-build /p:Version=${{ env.fullSemVer }}

    - name: Connect to Cygnus packages in GitHub
      run: dotnet nuget add source --username c49nu5 --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/c49nu5/index.json"

    - name: Publish
      run: dotnet nuget push **/bin/Release/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }}  --source "github"
