name: Publish

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: true

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3.2.1
      with:
        versionSpec: '6.3.x'
              
    - name: Determine Version
      id: version_step # step id used as a reference for output values
      uses: gittools/actions/gitversion/execute@v3.2.1

    - name: Display GitVersion variables
      run: |
        echo "FullSemVer (env.fullSemVer)    : ${{ env.fullSemVer }}"
        echo "SemVer (env.semVer)            : ${{ env.semVer }}"

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Install third party notices tool
      run: dotnet tool install --global ThirdLicense
      continue-on-error: true
      
    - name: Generate third party notices
      run: thirdlicense --project  ./Cygnus.BLE.API/Cygnus.BLE.API.csproj --output ./THIRD-PARTY-NOTICES.txt
      continue-on-error: true

    - name: Build
      run: dotnet build -c Release --no-restore /p:Version=${{ env.fullSemVer }}

    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal

    - name: Connect to Cygnus packages in GitHub
      run: dotnet nuget add source --username c49nu5 --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/c49nu5/index.json"

    - name: Publish
      run: dotnet nuget push **/bin/Release/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }}  --source "github"
